export const data = {
  directed: true,
  multigraph: false,
  graph: {},
  nodes: [
    {
      color: "#660000",
      id: "AT: Golondrina",
    },
    {
      color: "#660000",
      id: "AT: Passerines",
    },
    {
      color: "#660000",
      id: "AT: Communidad",
    },
    {
      color: "#660000",
      id: "AT: Pajaro brujo",
    },
    {
      color: "#660000",
      id: "AT: Bird health",
    },
    {
      color: "#660000",
      id: "Philornis downsi",
    },
    {
      color: "#660000",
      id: "Polistes versicolor",
    },
    {
      color: "#660000",
      id: "Pinzon de manglar",
    },
    {
      color: "#660000",
      id: "Aves en la costera",
    },
    {
      color: "#660000",
      id: "Aves marinas",
    },
    {
      color: "#660000",
      id: "Aves en carretera",
    },
    {
      color: "#660000",
      id: "Flamencos",
    },
    {
      color: "#660000",
      id: "Scalesia restoration",
    },
    {
      color: "#660000",
      id: "Imagenes satelitales",
    },
    {
      color: "#660000",
      id: "Ranas introducidas",
    },
    {
      color: "#660000",
      id: "Cascarilla",
    },
    {
      color: "#660000",
      id: "Ecologico submareal",
    },
    {
      color: "#660000",
      id: "Especies invasoras marinas",
    },
    {
      color: "#660000",
      id: "Tortuga verde",
    },
    {
      color: "#660000",
      id: "Pesquerias",
    },
    {
      color: "#660000",
      id: "Montes submarinos",
    },
    {
      color: "#660000",
      id: "GV: Practicas agricolas",
    },
    {
      color: "#660000",
      id: "GV: Restauracion ecologica",
    },
    {
      color: "#660000",
      id: "Tiburones en la RMG",
    },
    {
      color: "#660000",
      id: "Tortugas terrestres",
    },
    {
      color: "#cc0000",
      id: "Isabela",
    },
    {
      color: "#ea9999",
      id: "Progne modesta",
    },
    {
      color: "#1c4587",
      id: "Biodiversity conservation",
    },
    {
      color: "#1c4587",
      id: "Biodiversity",
    },
    {
      color: "#1c4587",
      id: "Biosecurity/invasive species",
    },
    {
      color: "#1c4587",
      id: "Population ecology/monitoring",
    },
    {
      color: "#00FA9A",
      id: "Terrestrial birds",
    },
    {
      color: "#00FA9A",
      id: "Insects",
    },
    {
      color: "#ED6D22",
      id: 2018,
    },
    {
      color: "#cc0000",
      id: "San Cristobal",
    },
    {
      color: "#cc0000",
      id: "Floreana",
    },
    {
      color: "#cc0000",
      id: "Pinzon",
    },
    {
      color: "#cc0000",
      id: "Rabida",
    },
    {
      color: "#1c4587",
      id: "Ecosystem restoration",
    },
    {
      color: "#00FA9A",
      id: "Darwin's finches",
    },
    {
      color: "#00FFFF",
      id: "Education",
    },
    {
      color: "#ea9999",
      id: "Pyrocephalus nanus",
    },
    {
      color: "#ea9999",
      id: "Rubus niveus",
    },
    {
      color: "#ea9999",
      id: "Sambucus nigra",
    },
    {
      color: "#1c4587",
      id: "Feeding ecology/food supply",
    },
    {
      color: "#1c4587",
      id: "Habitat loss/degradation/land use",
    },
    {
      color: "#00FA9A",
      id: "Terrestrial plants",
    },
    {
      color: "#1c4587",
      id: "Wildlife health",
    },
    {
      color: "#cc0000",
      id: "Genovesa",
    },
    {
      color: "#cc0000",
      id: "Espanola",
    },
    {
      color: "#cc0000",
      id: "Santa Fe",
    },
    {
      color: "#cc0000",
      id: "Fernandina",
    },
    {
      color: "#cc0000",
      id: "Santiago",
    },
    {
      color: "#cc0000",
      id: "Pinta",
    },
    {
      color: "#cc0000",
      id: "Baltra",
    },
    {
      color: "#cc0000",
      id: "Daphne Mayor",
    },
    {
      color: "#cc0000",
      id: "Marchena",
    },
    {
      color: "#cc0000",
      id: "Seymour Norte",
    },
    {
      color: "#cc0000",
      id: "Darwin",
    },
    {
      color: "#cc0000",
      id: "Wolf",
    },
    {
      color: "#FFFF00",
      id: "Tourism/ecotourism",
    },
    {
      color: "#ea9999",
      id: "Camarhynchus heliobates",
    },
    {
      color: "#ea9999",
      id: "Rattus spp",
    },
    {
      color: "#1c4587",
      id: "Extinction and extinction risk",
    },
    {
      color: "#ea9999",
      id: "Crotophaga ani",
    },
    {
      color: "#ea9999",
      id: "Spheniscus mendiculus",
    },
    {
      color: "#ea9999",
      id: "Phalacrocorax harrisi",
    },
    {
      color: "#ea9999",
      id: "Phoebastria irrorata",
    },
    {
      color: "#ea9999",
      id: "Felis catus",
    },
    {
      color: "#1c4587",
      id: "Direct human impacts",
    },
    {
      color: "#cc0000",
      id: "Islotes Marielas",
    },
    {
      color: "#3c78d8",
      id: "El Niño/La Niña event",
    },
    {
      color: "#3c78d8",
      id: "Meterology",
    },
    {
      color: "#3c78d8",
      id: "Oceanography",
    },
    {
      color: "#8A2BE2",
      id: "Marine mammals",
    },
    {
      color: "#ADFF2F",
      id: "Climate change impacts",
    },
    {
      color: "#FF69B4",
      id: "Transportation",
    },
    {
      color: "#cc0000",
      id: "Bainbridge",
    },
    {
      color: "#ea9999",
      id: "Anas bahamensis galapagensis",
    },
    {
      color: "#ea9999",
      id: "Gallinula galeata",
    },
    {
      color: "#ea9999",
      id: "Himantopus mexicanus",
    },
    {
      color: "#ea9999",
      id: "Leucophaeus fuliginosus",
    },
    {
      color: "#ea9999",
      id: "Haematopus palliatus galapagensis",
    },
    {
      color: "#ea9999",
      id: "Numenius phaeopus",
    },
    {
      color: "#ea9999",
      id: "Ardea blanca",
    },
    {
      color: "#ea9999",
      id: "Ardea herodias cognata",
    },
    {
      color: "#ea9999",
      id: "Nyctanassa violacea pauper",
    },
    {
      color: "#ea9999",
      id: "Podilymbus podiceps",
    },
    {
      color: "#ea9999",
      id: "Butorides striata sundevalli",
    },
    {
      color: "#ea9999",
      id: "Tringa sp.",
    },
    {
      color: "#1c4587",
      id: "Biogeography",
    },
    {
      color: "#ea9999",
      id: "Scalesia pedunculata",
    },
    {
      color: "#00FA9A",
      id: "Scalesia",
    },
    {
      color: "#ea9999",
      id: "Scinax quinquefasciatus",
    },
    {
      color: "#1c4587",
      id: "Genetics",
    },
    {
      color: "#00FA9A",
      id: "Terrestrial amphibians",
    },
    {
      color: "#ea9999",
      id: "Cinchona pubescens",
    },
    {
      color: "#8A2BE2",
      id: "Seaweed/algae",
    },
    {
      color: "#8A2BE2",
      id: "Corals",
    },
    {
      color: "#8A2BE2",
      id: "Marine invertebrates",
    },
    {
      color: "#8A2BE2",
      id: "Marine microogarnisms",
    },
    {
      color: "#8A2BE2",
      id: "Fish",
    },
    {
      color: "#8A2BE2",
      id: "Marine plants",
    },
    {
      color: "#ADFF2F",
      id: "Climate change adaptation",
    },
    {
      color: "#ea9999",
      id: "Caulerpa racemosa",
    },
    {
      color: "#ea9999",
      id: "Asparagopsis taxiformis",
    },
    {
      color: "#ea9999",
      id: "Carijoa riisei",
    },
    {
      color: "#1c4587",
      id: "Behavioural ecology",
    },
    {
      color: "#cc0000",
      id: "Bartolome",
    },
    {
      color: "#ea9999",
      id: "Chelonia mydas",
    },
    {
      color: "#8A2BE2",
      id: "Marine reptiles",
    },
    {
      color: "#ea9999",
      id: "Pontinus clemensi",
    },
    {
      color: "#ea9999",
      id: "Paralabrax albomaculatus",
    },
    {
      color: "#ea9999",
      id: "Thunnus albacares",
    },
    {
      color: "#ea9999",
      id: "Acanthocybium solandri",
    },
    {
      color: "#ea9999",
      id: "Sardinops sagax",
    },
    {
      color: "#ea9999",
      id: "Mycteroperca olfax",
    },
    {
      color: "#ea9999",
      id: "Lutjanus argentiventris",
    },
    {
      color: "#ea9999",
      id: "Epinephelus mystacinus",
    },
    {
      color: "#ea9999",
      id: "Caulolatilus princeps",
    },
    {
      color: "#1c4587",
      id: "Natural resource management",
    },
    {
      color: "#1c4587",
      id: "Illegal fishing/overfishing",
    },
    {
      color: "#1c4587",
      id: "Ecosystem services",
    },
    {
      color: "#008B8B",
      id: "Fisheries/aquaculture",
    },
    {
      color: "#008B8B",
      id: "Local food production",
    },
    {
      color: "#00FFFF",
      id: "Artisans",
    },
    {
      color: "#3c78d8",
      id: "Volcanoes/seamounts",
    },
    {
      color: "#1c4587",
      id: "Taxonomy",
    },
    {
      color: "#ADFF2F",
      id: "Climate change patterns",
    },
    {
      color: "#FF69B4",
      id: "Innovation",
    },
    {
      color: "#008B8B",
      id: "Agriculture",
    },
    {
      color: "#ea9999",
      id: "Opuntia echios",
    },
    {
      color: "#ea9999",
      id: "Acacia macracantha",
    },
    {
      color: "#ea9999",
      id: "Bursera malacophylla",
    },
    {
      color: "#ea9999",
      id: "Parkinsonia aculeata",
    },
    {
      color: "#ea9999",
      id: "Castella galapageia",
    },
    {
      color: "#ea9999",
      id: "Piscidia carthagenensis",
    },
    {
      color: "#ea9999",
      id: "Croton scouleri",
    },
    {
      color: "#ea9999",
      id: "Psidium galapageium",
    },
    {
      color: "#ea9999",
      id: "Darwiniothamnus tenuifolius",
    },
    {
      color: "#ea9999",
      id: "Opuntia megasperma",
    },
    {
      color: "#1c4587",
      id: "Socio-ecological systems",
    },
    {
      color: "#ea9999",
      id: "Galeocerdo cuvier",
    },
    {
      color: "#ea9999",
      id: "Sphyrna lewini",
    },
    {
      color: "#ea9999",
      id: "Carcharhinus galapagensis",
    },
    {
      color: "#8A2BE2",
      id: "Sharks and rays",
    },
    {
      color: "#ea9999",
      id: "Chelonoidis",
    },
    {
      color: "#00FA9A",
      id: "Terrestrial reptiles",
    },
    {
      color: "#cccccc",
      id: "2018",
    },
  ],
  links: [
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Golondrina",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#660000",
      source: "AT: Golondrina",
      target: "Philornis downsi",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "AT: Golondrina",
      target: "Progne modesta",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Golondrina",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Golondrina",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Golondrina",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Golondrina",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Golondrina",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Golondrina",
      target: "Insects",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "AT: Golondrina",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Passerines",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Passerines",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Passerines",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Passerines",
      target: "Pinzon",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Passerines",
      target: "Rabida",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Passerines",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Passerines",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Passerines",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Passerines",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Passerines",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Passerines",
      target: "Darwin's finches",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "AT: Passerines",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Communidad",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Communidad",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Communidad",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Communidad",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Communidad",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Communidad",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Communidad",
      target: "Darwin's finches",
    },
    {
      weight: 1,
      color: "#00FFFF",
      source: "AT: Communidad",
      target: "Education",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "AT: Communidad",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "AT: Pajaro brujo",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#660000",
      source: "AT: Pajaro brujo",
      target: "Philornis downsi",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "AT: Pajaro brujo",
      target: "Pyrocephalus nanus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "AT: Pajaro brujo",
      target: "Rubus niveus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "AT: Pajaro brujo",
      target: "Sambucus nigra",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Feeding ecology/food supply",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Habitat loss/degradation/land use",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Pajaro brujo",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Pajaro brujo",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Pajaro brujo",
      target: "Insects",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Pajaro brujo",
      target: "Terrestrial plants",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "AT: Pajaro brujo",
      target: "2018",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "AT: Bird health",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Bird health",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "AT: Bird health",
      target: "Darwin's finches",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "AT: Bird health",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Genovesa",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Espanola",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Santa Fe",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Fernandina",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Pinzon",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Santiago",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Pinta",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Baltra",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Daphne Mayor",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Marchena",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Rabida",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Seymour Norte",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Darwin",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Philornis downsi",
      target: "Wolf",
    },
    {
      weight: 1,
      color: "#660000",
      source: "Philornis downsi",
      target: "Philornis downsi",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Philornis downsi",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Philornis downsi",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Philornis downsi",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Philornis downsi",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Philornis downsi",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Philornis downsi",
      target: "Darwin's finches",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Philornis downsi",
      target: "Insects",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Philornis downsi",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Polistes versicolor",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Polistes versicolor",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Polistes versicolor",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#660000",
      source: "Polistes versicolor",
      target: "Polistes versicolor",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Polistes versicolor",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Polistes versicolor",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Polistes versicolor",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Polistes versicolor",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Polistes versicolor",
      target: "Insects",
    },
    {
      weight: 1,
      color: "#FFFF00",
      source: "Polistes versicolor",
      target: "Tourism/ecotourism",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Polistes versicolor",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Pinzon de manglar",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#660000",
      source: "Pinzon de manglar",
      target: "Philornis downsi",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pinzon de manglar",
      target: "Camarhynchus heliobates",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pinzon de manglar",
      target: "Rattus spp",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pinzon de manglar",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pinzon de manglar",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pinzon de manglar",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pinzon de manglar",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pinzon de manglar",
      target: "Extinction and extinction risk",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pinzon de manglar",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Pinzon de manglar",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Pinzon de manglar",
      target: "Darwin's finches",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Pinzon de manglar",
      target: "Insects",
    },
    {
      weight: 1,
      color: "#00FFFF",
      source: "Pinzon de manglar",
      target: "Education",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Pinzon de manglar",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Aves en la costera",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Aves en la costera",
      target: "Fernandina",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves en la costera",
      target: "Crotophaga ani",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves en la costera",
      target: "Spheniscus mendiculus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves en la costera",
      target: "Rattus spp",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves en la costera",
      target: "Phalacrocorax harrisi",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves en la costera",
      target: "Phoebastria irrorata",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves en la costera",
      target: "Felis catus",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en la costera",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en la costera",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en la costera",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en la costera",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en la costera",
      target: "Direct human impacts",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en la costera",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Aves en la costera",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Aves en la costera",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Aves marinas",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Aves marinas",
      target: "Espanola",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Aves marinas",
      target: "Fernandina",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Aves marinas",
      target: "Islotes Marielas",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves marinas",
      target: "Crotophaga ani",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves marinas",
      target: "Spheniscus mendiculus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves marinas",
      target: "Rattus spp",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves marinas",
      target: "Phalacrocorax harrisi",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves marinas",
      target: "Phoebastria irrorata",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Aves marinas",
      target: "Felis catus",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Aves marinas",
      target: "El Niño/La Niña event",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Aves marinas",
      target: "Meterology",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Aves marinas",
      target: "Oceanography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves marinas",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves marinas",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves marinas",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves marinas",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves marinas",
      target: "Direct human impacts",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves marinas",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Aves marinas",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Aves marinas",
      target: "Marine mammals",
    },
    {
      weight: 1,
      color: "#ADFF2F",
      source: "Aves marinas",
      target: "Climate change impacts",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Aves marinas",
      target: "2018",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en carretera",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en carretera",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Aves en carretera",
      target: "Direct human impacts",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Aves en carretera",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Aves en carretera",
      target: "Darwin's finches",
    },
    {
      weight: 1,
      color: "#FF69B4",
      source: "Aves en carretera",
      target: "Transportation",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Aves en carretera",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Flamencos",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Flamencos",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Flamencos",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Flamencos",
      target: "Santiago",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Flamencos",
      target: "Rabida",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Flamencos",
      target: "Bainbridge",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Anas bahamensis galapagensis",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Gallinula galeata",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Himantopus mexicanus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Leucophaeus fuliginosus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Haematopus palliatus galapagensis",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Numenius phaeopus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Ardea blanca",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Ardea herodias cognata",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Nyctanassa violacea pauper",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Podilymbus podiceps",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Butorides striata sundevalli",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Flamencos",
      target: "Tringa sp.",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Flamencos",
      target: "El Niño/La Niña event",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Biogeography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Direct human impacts",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Flamencos",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Flamencos",
      target: "Terrestrial birds",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Flamencos",
      target: "2018",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Scalesia restoration",
      target: "Rubus niveus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Scalesia restoration",
      target: "Scalesia pedunculata",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Scalesia restoration",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Scalesia restoration",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Scalesia restoration",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Scalesia restoration",
      target: "Habitat loss/degradation/land use",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Scalesia restoration",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Scalesia restoration",
      target: "Insects",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Scalesia restoration",
      target: "Terrestrial plants",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Scalesia restoration",
      target: "Scalesia",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Scalesia restoration",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Imagenes satelitales",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Imagenes satelitales",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Imagenes satelitales",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Imagenes satelitales",
      target: "Santiago",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Imagenes satelitales",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Imagenes satelitales",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Imagenes satelitales",
      target: "Biogeography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Imagenes satelitales",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Imagenes satelitales",
      target: "Terrestrial plants",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Imagenes satelitales",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Ranas introducidas",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Ranas introducidas",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Ranas introducidas",
      target: "Scinax quinquefasciatus",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Biogeography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Genetics",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ranas introducidas",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Ranas introducidas",
      target: "Terrestrial amphibians",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Ranas introducidas",
      target: "2018",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Cascarilla",
      target: "Rubus niveus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Cascarilla",
      target: "Cinchona pubescens",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Genetics",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Cascarilla",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Cascarilla",
      target: "Terrestrial plants",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Cascarilla",
      target: "2018",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Ecologico submareal",
      target: "El Niño/La Niña event",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Ecologico submareal",
      target: "Oceanography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ecologico submareal",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ecologico submareal",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ecologico submareal",
      target: "Biogeography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Ecologico submareal",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Ecologico submareal",
      target: "Seaweed/algae",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Ecologico submareal",
      target: "Corals",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Ecologico submareal",
      target: "Marine invertebrates",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Ecologico submareal",
      target: "Marine microogarnisms",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Ecologico submareal",
      target: "Fish",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Ecologico submareal",
      target: "Marine plants",
    },
    {
      weight: 1,
      color: "#ADFF2F",
      source: "Ecologico submareal",
      target: "Climate change adaptation",
    },
    {
      weight: 1,
      color: "#ADFF2F",
      source: "Ecologico submareal",
      target: "Climate change impacts",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Ecologico submareal",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Especies invasoras marinas",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Especies invasoras marinas",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Especies invasoras marinas",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Especies invasoras marinas",
      target: "Baltra",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Especies invasoras marinas",
      target: "Caulerpa racemosa",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Especies invasoras marinas",
      target: "Asparagopsis taxiformis",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Especies invasoras marinas",
      target: "Carijoa riisei",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Especies invasoras marinas",
      target: "El Niño/La Niña event",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Especies invasoras marinas",
      target: "Oceanography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Especies invasoras marinas",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Especies invasoras marinas",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Especies invasoras marinas",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Especies invasoras marinas",
      target: "Behavioural ecology",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Especies invasoras marinas",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Especies invasoras marinas",
      target: "Seaweed/algae",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Especies invasoras marinas",
      target: "Marine invertebrates",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Especies invasoras marinas",
      target: "Marine microogarnisms",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Especies invasoras marinas",
      target: "Marine plants",
    },
    {
      weight: 1,
      color: "#ADFF2F",
      source: "Especies invasoras marinas",
      target: "Climate change impacts",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Especies invasoras marinas",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Tortuga verde",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Tortuga verde",
      target: "Fernandina",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Tortuga verde",
      target: "Baltra",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Tortuga verde",
      target: "Bartolome",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Tortuga verde",
      target: "Chelonia mydas",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortuga verde",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortuga verde",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortuga verde",
      target: "Behavioural ecology",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortuga verde",
      target: "Direct human impacts",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Tortuga verde",
      target: "Marine reptiles",
    },
    {
      weight: 1,
      color: "#FF69B4",
      source: "Tortuga verde",
      target: "Transportation",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Tortuga verde",
      target: "2018",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Pontinus clemensi",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Paralabrax albomaculatus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Thunnus albacares",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Acanthocybium solandri",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Sardinops sagax",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Mycteroperca olfax",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Lutjanus argentiventris",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Epinephelus mystacinus",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Pesquerias",
      target: "Caulolatilus princeps",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Pesquerias",
      target: "Oceanography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pesquerias",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pesquerias",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pesquerias",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pesquerias",
      target: "Natural resource management",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pesquerias",
      target: "Illegal fishing/overfishing",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Pesquerias",
      target: "Ecosystem services",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Pesquerias",
      target: "Fish",
    },
    {
      weight: 1,
      color: "#ADFF2F",
      source: "Pesquerias",
      target: "Climate change impacts",
    },
    {
      weight: 1,
      color: "#008B8B",
      source: "Pesquerias",
      target: "Fisheries/aquaculture",
    },
    {
      weight: 1,
      color: "#008B8B",
      source: "Pesquerias",
      target: "Local food production",
    },
    {
      weight: 1,
      color: "#00FFFF",
      source: "Pesquerias",
      target: "Artisans",
    },
    {
      weight: 1,
      color: "#00FFFF",
      source: "Pesquerias",
      target: "Education",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Pesquerias",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Montes submarinos",
      target: "Santa Fe",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Montes submarinos",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Montes submarinos",
      target: "Oceanography",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Montes submarinos",
      target: "Volcanoes/seamounts",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Montes submarinos",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Montes submarinos",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Montes submarinos",
      target: "Biogeography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Montes submarinos",
      target: "Genetics",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Montes submarinos",
      target: "Natural resource management",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Montes submarinos",
      target: "Taxonomy",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Montes submarinos",
      target: "Seaweed/algae",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Montes submarinos",
      target: "Corals",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Montes submarinos",
      target: "Marine invertebrates",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Montes submarinos",
      target: "Marine microogarnisms",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Montes submarinos",
      target: "Fish",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Montes submarinos",
      target: "Marine plants",
    },
    {
      weight: 1,
      color: "#ADFF2F",
      source: "Montes submarinos",
      target: "Climate change patterns",
    },
    {
      weight: 1,
      color: "#00FFFF",
      source: "Montes submarinos",
      target: "Education",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Montes submarinos",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "GV: Practicas agricolas",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Natural resource management",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Habitat loss/degradation/land use",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Practicas agricolas",
      target: "Ecosystem services",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "GV: Practicas agricolas",
      target: "Terrestrial plants",
    },
    {
      weight: 1,
      color: "#FF69B4",
      source: "GV: Practicas agricolas",
      target: "Innovation",
    },
    {
      weight: 1,
      color: "#008B8B",
      source: "GV: Practicas agricolas",
      target: "Agriculture",
    },
    {
      weight: 1,
      color: "#008B8B",
      source: "GV: Practicas agricolas",
      target: "Local food production",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "GV: Practicas agricolas",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "GV: Restauracion ecologica",
      target: "San Cristobal",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "GV: Restauracion ecologica",
      target: "Espanola",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "GV: Restauracion ecologica",
      target: "Floreana",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "GV: Restauracion ecologica",
      target: "Baltra",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Opuntia echios",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Scalesia pedunculata",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Acacia macracantha",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Bursera malacophylla",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Parkinsonia aculeata",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Castella galapageia",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Piscidia carthagenensis",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Croton scouleri",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Psidium galapageium",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Darwiniothamnus tenuifolius",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "GV: Restauracion ecologica",
      target: "Opuntia megasperma",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Biosecurity/invasive species",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Natural resource management",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Habitat loss/degradation/land use",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Ecosystem restoration",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "GV: Restauracion ecologica",
      target: "Socio-ecological systems",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "GV: Restauracion ecologica",
      target: "Terrestrial plants",
    },
    {
      weight: 1,
      color: "#FF69B4",
      source: "GV: Restauracion ecologica",
      target: "Innovation",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "GV: Restauracion ecologica",
      target: "2018",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Tiburones en la RMG",
      target: "Chelonia mydas",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Tiburones en la RMG",
      target: "Galeocerdo cuvier",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Tiburones en la RMG",
      target: "Sphyrna lewini",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Tiburones en la RMG",
      target: "Carcharhinus galapagensis",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Tiburones en la RMG",
      target: "El Niño/La Niña event",
    },
    {
      weight: 1,
      color: "#3c78d8",
      source: "Tiburones en la RMG",
      target: "Oceanography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tiburones en la RMG",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tiburones en la RMG",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tiburones en la RMG",
      target: "Biogeography",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tiburones en la RMG",
      target: "Feeding ecology/food supply",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tiburones en la RMG",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tiburones en la RMG",
      target: "Genetics",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Tiburones en la RMG",
      target: "Marine reptiles",
    },
    {
      weight: 1,
      color: "#8A2BE2",
      source: "Tiburones en la RMG",
      target: "Sharks and rays",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Tiburones en la RMG",
      target: "2018",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Tortugas terrestres",
      target: "Isabela",
    },
    {
      weight: 1,
      color: "#cc0000",
      source: "Tortugas terrestres",
      target: "Espanola",
    },
    {
      weight: 1,
      color: "#ea9999",
      source: "Tortugas terrestres",
      target: "Chelonoidis",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Biodiversity conservation",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Biodiversity",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Behavioural ecology",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Population ecology/monitoring",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Wildlife health",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Ecosystem services",
    },
    {
      weight: 1,
      color: "#1c4587",
      source: "Tortugas terrestres",
      target: "Socio-ecological systems",
    },
    {
      weight: 1,
      color: "#00FA9A",
      source: "Tortugas terrestres",
      target: "Terrestrial reptiles",
    },
    {
      weight: 1,
      color: "#00FFFF",
      source: "Tortugas terrestres",
      target: "Education",
    },
    {
      weight: 1,
      color: "#cccccc",
      source: "Tortugas terrestres",
      target: "2018",
    },
  ],
};