export const data = {
  directed: true,
  multigraph: true,
  graph: {},
  nodes: [
    {
      size: 0.09594363415217112,
      id: "1.4",
    },
    {
      size: 0.05389238644932745,
      id: "2.2",
    },
    {
      size: 0.04322319221600124,
      id: "2.3",
    },
    {
      size: 0.05296089396889758,
      id: "2.4",
    },
    {
      size: 0.040631571911863694,
      id: "2.a",
    },
    {
      size: 0.08165511813615521,
      id: "3.5",
    },
    {
      size: 0.10676438898890454,
      id: "3.7",
    },
    {
      size: 0.09047556513972838,
      id: "3.8",
    },
    {
      size: 0.07938643738555942,
      id: "3.c",
    },
    {
      size: 0.06843327185892424,
      id: "4.1",
    },
    {
      size: 0.04948584625774818,
      id: "4.2",
    },
    {
      size: 0.11813688007189775,
      id: "4.3",
    },
    {
      size: 0.07148789249332164,
      id: "4.4",
    },
    {
      size: 0.12390104602318945,
      id: "4.7",
    },
    {
      size: 0.09783361055877995,
      id: "4.c",
    },
    {
      size: 0.14102646992414866,
      id: "5.2",
    },
    {
      size: 0.04747715313629027,
      id: "6.1",
    },
    {
      size: 0.08760451864108697,
      id: "6.2",
    },
    {
      size: 0.041631054077686865,
      id: "6.3",
    },
    {
      size: 0.03844661911481272,
      id: "6.4",
    },
    {
      size: 0.06537815380454014,
      id: "7.b",
    },
    {
      size: 0.06101263653976359,
      id: "8.2",
    },
    {
      size: 0.05147050216260146,
      id: "8.6",
    },
    {
      size: 0.07740462222671263,
      id: "8.9",
    },
    {
      size: 0.08634279121801502,
      id: "9.5",
    },
    {
      size: 0.07215641669000238,
      id: "9.c",
    },
    {
      size: 0.04976717456357608,
      id: "11.2",
    },
    {
      size: 0.06411354797945001,
      id: "11.3",
    },
    {
      size: 0.08718612273981231,
      id: "11.4",
    },
    {
      size: 0.046332986017700584,
      id: "11.b",
    },
    {
      size: 0.053706787126372925,
      id: "12.2",
    },
    {
      size: 0.050457100987092454,
      id: "12.5",
    },
    {
      size: 0.05008913663422854,
      id: "14.1",
    },
    {
      size: 0.07892485601887407,
      id: "14.2",
    },
    {
      size: 0.07232463385179044,
      id: "14.4",
    },
    {
      size: 0.05965697908539613,
      id: "15.5",
    },
    {
      size: 0.037017125768870354,
      id: "15.7",
    },
    {
      size: 0.04526598246180458,
      id: "15.8",
    },
    {
      size: 0.08614948609935213,
      id: "16.2",
    },
    {
      size: 0.1337596540666881,
      id: "16.5",
    },
  ],
  links: [
    {
      weight: 3.0,
      source: "1.4",
      target: "2.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "1.4",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "3.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "5.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "1.4",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "9.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "1.4",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "11.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "11.3",
      key: 0,
    },
    {
      weight: -2.0,
      source: "1.4",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "1.4",
      target: "16.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "3.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "3.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "9.5",
      key: 0,
    },
    {
      weight: -1.0,
      source: "2.2",
      target: "9.c",
      key: 0,
    },
    {
      weight: -1.0,
      source: "2.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "14.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.2",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.2",
      target: "16.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.3",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.3",
      target: "2.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.3",
      target: "2.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.3",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.3",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "8.6",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.3",
      target: "8.9",
      key: 0,
    },
    {
      weight: -2.0,
      source: "2.3",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.3",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "2.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.4",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "6.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.4",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.4",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.4",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.4",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.4",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.a",
      target: "1.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.a",
      target: "2.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.a",
      target: "2.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.a",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "6.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.a",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.a",
      target: "7.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "2.a",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "9.c",
      key: 0,
    },
    {
      weight: -2.0,
      source: "2.a",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "2.a",
      target: "15.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "2.a",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "1.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.5",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.5",
      target: "4.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "4.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.5",
      target: "5.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.5",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.5",
      target: "16.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "1.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.7",
      target: "3.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.7",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "3.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "4.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.7",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.7",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.7",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "11.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.7",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.7",
      target: "16.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.8",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "2.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.8",
      target: "3.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.8",
      target: "3.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "3.8",
      target: "3.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.8",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.8",
      target: "16.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "3.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "3.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "3.c",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "3.c",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "2.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.1",
      target: "3.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.1",
      target: "3.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.1",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.1",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.1",
      target: "4.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.1",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.1",
      target: "4.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.1",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.2",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.2",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.2",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.2",
      target: "4.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.2",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.2",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.2",
      target: "11.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.2",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "3.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "4.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "9.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "11.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.3",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "14.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "15.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.3",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.3",
      target: "16.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.4",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "2.a",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.4",
      target: "3.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.4",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.4",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.4",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.4",
      target: "7.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.4",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.4",
      target: "8.6",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.4",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.4",
      target: "9.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.4",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.4",
      target: "14.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.4",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "3.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.7",
      target: "4.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.7",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.7",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.7",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "11.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.7",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.7",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.7",
      target: "14.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "15.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "15.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "16.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.7",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "3.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.c",
      target: "3.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "4.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.c",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.c",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "4.c",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "5.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "9.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "4.c",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "16.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "4.c",
      target: "16.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "5.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "3.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "3.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "4.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "11.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "5.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "5.2",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "16.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "5.2",
      target: "16.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.1",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.1",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.1",
      target: "6.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.1",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "9.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.1",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.1",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.1",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.1",
      target: "16.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.2",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.2",
      target: "2.a",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "3.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.2",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "6.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "6.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.2",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.2",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.2",
      target: "11.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "12.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.2",
      target: "14.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.2",
      target: "15.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.3",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.3",
      target: "6.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.3",
      target: "6.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.3",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.3",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.3",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.3",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.3",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.4",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.4",
      target: "2.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.4",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.4",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.4",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.4",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.4",
      target: "3.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.4",
      target: "6.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.4",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.4",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.4",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.4",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "6.4",
      target: "11.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.4",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "6.4",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "6.4",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "3.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "7.b",
      target: "4.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "6.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "7.b",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "7.b",
      target: "9.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "11.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "11.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "7.b",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "7.b",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "3.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.2",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.2",
      target: "9.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "9.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.2",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.2",
      target: "16.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.6",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "2.a",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.6",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.6",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.6",
      target: "4.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.6",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.6",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "9.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.6",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.6",
      target: "16.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "5.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "7.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.9",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.9",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.9",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "8.9",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "14.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "8.9",
      target: "15.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "8.9",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "2.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "2.a",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "4.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "7.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "9.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "11.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.5",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "14.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.5",
      target: "15.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.5",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "3.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "4.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "4.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "6.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.c",
      target: "7.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "9.c",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "11.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "11.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "9.c",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "14.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "9.c",
      target: "16.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.2",
      target: "2.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.2",
      target: "3.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.2",
      target: "4.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "4.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "4.4",
      key: 0,
    },
    {
      weight: -1.0,
      source: "11.2",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.2",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.2",
      target: "8.6",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.2",
      target: "11.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.2",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "12.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.2",
      target: "15.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.2",
      target: "15.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "3.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "3.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "5.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "6.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "6.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "6.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "6.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "9.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "9.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.3",
      target: "11.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.3",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.3",
      target: "15.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.4",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.4",
      target: "2.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "4.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.4",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.4",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.4",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.4",
      target: "8.6",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.4",
      target: "9.5",
      key: 0,
    },
    {
      weight: -1.0,
      source: "11.4",
      target: "11.2",
      key: 0,
    },
    {
      weight: -1.0,
      source: "11.4",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "12.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "14.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "15.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "11.4",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.4",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.b",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "4.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "11.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "11.b",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "12.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "14.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "14.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "11.b",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.2",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "6.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.2",
      target: "6.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.2",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "7.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "9.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.2",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "14.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.2",
      target: "14.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.2",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.2",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "4.c",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "6.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "7.b",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "11.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.5",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "12.5",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "12.5",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "12.5",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.1",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "6.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "11.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.1",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.1",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.1",
      target: "12.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.1",
      target: "14.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.1",
      target: "14.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.1",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.1",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "6.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "7.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.2",
      target: "11.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "12.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "12.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "14.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "15.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.2",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.2",
      target: "16.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.4",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.4",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "4.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "4.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "5.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "6.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "8.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "9.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "11.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.4",
      target: "12.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "14.4",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.4",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "14.4",
      target: "16.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "14.4",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.5",
      target: "6.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.5",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.5",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.5",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "11.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "11.b",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "12.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "14.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "14.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "15.7",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.5",
      target: "15.8",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.5",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.7",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.7",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.7",
      target: "4.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.7",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.7",
      target: "9.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.7",
      target: "11.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.7",
      target: "12.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.7",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.7",
      target: "14.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.7",
      target: "15.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.7",
      target: "16.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "1.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.8",
      target: "2.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.8",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "2.a",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.8",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "6.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "8.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "8.6",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "9.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.8",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "11.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.8",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "15.8",
      target: "14.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "15.8",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "15.8",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "1.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "2.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "2.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "2.a",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "3.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "3.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "3.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "4.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "4.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "4.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "4.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "5.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "8.9",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "9.5",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "11.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "11.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "14.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "15.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.2",
      target: "15.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.2",
      target: "15.8",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.2",
      target: "16.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "1.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "2.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "2.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "2.a",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "3.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "3.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "3.c",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "4.1",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "4.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "4.3",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "4.4",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "4.7",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "4.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "5.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "6.1",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "6.2",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "6.3",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "7.b",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "8.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "8.6",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "8.9",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "9.5",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "9.c",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "11.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "11.3",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "11.4",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "12.2",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "14.1",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "14.2",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "14.4",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "15.5",
      key: 0,
    },
    {
      weight: 3.0,
      source: "16.5",
      target: "15.7",
      key: 0,
    },
    {
      weight: 1.0,
      source: "16.5",
      target: "15.8",
      key: 0,
    },
    {
      weight: 2.0,
      source: "16.5",
      target: "16.2",
      key: 0,
    },
  ],
};